name: Metrics

on:
  # Schedule updates (every 3 hours)
  schedule: [{cron: "0 */3 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: PROFILE
    permissions:
      contents: write

    steps:
        uses: lowlighter/metrics@latest
        with:
          username: yonasuriv
          token: ${{ secrets.METRICS_TOKEN }}
