# This has been forked (security reasons) from lowlighter, all kudos to him

# https://github.com/yonasuriv/metrics/blob/master/source/plugins/README.md
# To view examples of plugin deployment refer to the examples.yml file

name: Update Metrics

on:
  # Think about the planet, no need to update stats too frequently
  schedule: [{cron: "0 16 * * *"}]
  
  # Schedule updates (every 3 hours)
  # schedule: [{cron: "0 */3 * * *"}]
  
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: Profile
    permissions:
      contents: write

    steps:
      - name: General Metrics
        uses: lowlighter/metrics@latest
        with:
          # user: yonasuriv
          filename: source/plugins/metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Copenhagen
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - read:user
          #  - read:org
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          plugin_gists: no

      - name: Lines
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/lines/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4

      - name: Contributions Calendar
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/calendar/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/contributions-full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # can be half-year or full-year
          
      - name: Habits
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/habits/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts_type: classic # can be classic or graph
          plugin_habits_days: 14
          plugin_habits_from: 200

      - name: Programming Languages
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/languages/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15

      - name: Traffic
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/traffic/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_traffic: yes

      - name: Achievements
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/achievements/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/achievements-detailed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_limit: 12 # 0 to disable
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed # can be detailed or compact
          # plugin_achievements_threshold: X # Displays achievements not yet unlocked
          # plugin_achievements_ignored: 
            # Options: polyglot, stargazer, sponsor, deployer, member, maintainer, developer, scripter, packager, explorer, infographile, manager

      - name: Featured Repositories
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/repositories/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/featured.repos.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: yonasuriv/datasonda, yonasuriv/panicsonda, yonasuriv/stringshark, yonasuriv/metrics
          
      - name: Stargazers
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/stargazers/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: no
          plugin_stargazers_charts: no

      - name: Starred Topics
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/stars/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/starred.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          # plugin_topics_limit: 0
          plugin_topics_sort: stars # can be stars, activity, starred (date) or random
          plugin_topics_mode: icons # can be icons or labels
          
      - name: MBTI Personality Profile
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/community/16personalities/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/profile.mbti # metrics.plugin.16personalities.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_16personalities: yes
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
          plugin_16personalities_sections: personality, profile, traits
          plugin_16personalities_scores: yes

      - name: Steam Profile
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/steam/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/profile.steam-most
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: ${{ secrets.STEAM_USER }} # 0
          plugin_steam_sections: player, most-played # can be player, most-played, recently-played
          plugin_steam_games_limit: 8
          plugin_steam_recent_games_limit: 0
          plugin_steam_achievements_limit: 0

      - name: Spotify Profile
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/music/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/profile.spotify
          token: NOT_NEEDED
          base: ""
          plugin_music: no
          plugin_music_provider: spotify
          # plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          # plugin_music_user: 
          plugin_music_limit: 4
          plugin_music_mode: top # can be playlist (random track from url), recent or top (artists/tracks)
          plugin_music_top_type: artists # can be artists or tracks
          plugin_music_time_range: long # can be short (1 month), medium (6 months) or long (all time)
          plugin_music_playlist: https://open.spotify.com/embed/playlist/6VaxKvULieRunSsPwq1BVJ
          
      - name: RSS Feeds
      # https://github.com/yonasuriv/metrics/blob/master/source/plugins/rss/README.md
        uses: lowlighter/metrics@latest
        with:
          filename: source/plugins/rss.feed.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: no
          plugin_rss_limit: 4
          plugin_rss_source: https://news.ycombinator.com/rss

      - name: Remove Artifacts
        run: rm -rf "/github-metrics.svg"