name: Metrics

on:
  # Think about the planet, no need to update stats too frequently
  schedule: [{cron: "0 16 * * *"}]
  
  # Schedule updates (every 3 hours)
  # schedule: [{cron: "0 */3 * * *"}]
  
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: PROFILE
    permissions:
      contents: write

    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          # user: yonasuriv
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Copenhagen
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - read:user
          #  - read:org
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: yes
          plugin_achievements: yes
          plugin_languages: yes
          plugin_skyline: yes
          plugin_music: yes
          
      - name: MBTI Personality profile
        uses: lowlighter/metrics@latest
        if: ${{ success() || failure() }}
        with:
          filename: metrics.plugin.MBTI.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_16personalities: yes
          plugin_16personalities_scores: yes
          plugin_16personalities_sections: personality, traits
          plugin_16personalities_url: ${{ secrets.16personalities.com/profiles/b293e70d24e12 }}
          
